version: 0.2

env:
  variables:
    AWS_REGION: ap-south-1
    AWS_ACCOUNT_ID: 662905738256
    ECR_REPOSITORY: myecr1
    IMAGE_TAG: v1
    CLUSTER_NAME: dev-cluster
    DEPLOYMENT_NAME: myapp

phases:

  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 662905738256.dkr.ecr.ap-south-1.amazonaws.com

      - REPOSITORY_URI=662905738256.dkr.ecr.ap-south-1.amazonaws.com/myecr1

  build:
    commands:
      - echo Building Docker image...
      - docker build -t kube:v1 ./TestProject1
      - docker tag kube:v1 662905738256.dkr.ecr.ap-south-1.amazonaws.com/myecr1:v1

  post_build:
    commands:
      - echo Pushing Docker image...
      - docker push 662905738256.dkr.ecr.ap-south-1.amazonaws.com/myecr1:v1

      # Optional EKS deployment
      # - echo Updating kubeconfig...
      # - aws eks update-kubeconfig --region ap-south-1 --name dev-cluster

      # - echo Deploying to EKS...
      # - kubectl set image deployment/myapp \
      #     myapp=662905738256.dkr.ecr.ap-south-1.amazonaws.com/myecr1:v1

      # - kubectl rollout status deployment/myapp

artifacts:
  files:
    - '**/*'