version: "3.9"

# services:
#   djangoapp:
#     container_name: djangoapp
#     build: .
#     image: backend_ibm:latest
#     ports:
#       - "8004:8004"
#     env_file:
#       - .env

services:
  djangoapp:
    container_name: djangoapp
    build: .
    image: kube:latest
    network_mode: host
    ports:
      - "8000:8000"
      # - "80:80"
    env_file:
      - .env
      # - .env
      # - /home/ubuntu/wealthgrowth/.env

    # volumes:
    #   - "/home/ubuntu/wealthgrowth/media:/app/media"