# Generated by Django 5.2.13 on 2026-05-04 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='education',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.education'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='sports',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='app1.sports'),
        ),
    ]
